on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-uri: https://npm.pkg.github.com/
          scope: '@tdf-labs'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
